name: FastOperation
version: 1.0.0
description: A dart package for essential quick conversions.
repository: https://github.com/shantanu1k/FastOperation/
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter